package com.infiniteconquest.core;

public record GameEvent(long sequence, int turnNumber, int playerId, Type type, String detail) {
    public enum Type {
        MATCH_STARTED, MULLIGAN_COMPLETED, PHASE_CHANGED, TURN_STARTED, CARD_DRAWN, DRAW_FAILED,
        EXHAUSTION_DAMAGE, GP_GENERATED, GP_SPENT, CARDS_UNTAPPED, CARD_PLAYED, CHARACTER_MOVED,
        ATTACK_RESOLVED, OPPORTUNITY_ATTACK, CARD_DESTROYED, CAPITALS_REVEALED, CAPITAL_PASSIVE_TRIGGERED,
        DEVELOPMENT_PASSIVE_TRIGGERED,
        CARD_ABILITY_TRIGGERED, TERRAIN_TRIGGERED,
        GAME_OVER, TURN_ENDED
    }
}
