package com.infiniteconquest.net;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.infiniteconquest.core.GameSnapshot;

import java.util.List;

/**
 * Line-delimited JSON wire protocol for loopback online play.
 *
 * <p>Every message is one JSON object per line with a {@code "type"} tag.
 * Envelope types: {@code hello}, {@code start}, {@code command},
 * {@code mulligan}, {@code reaction}, {@code lobby}, {@code snapshot},
 * {@code state_update}, {@code game_over}, {@code error},
 * {@code mulligan_prompt}, {@code mulligan_update}, {@code reaction_prompt},
 * {@code reaction_timeout}.
 * There is no chat in alpha, and no chat envelope exists.
 *
 * <p>The wire carries only: player UUIDs, display names, deck lists (to the host
 * only), game commands, and redacted state. See {@code net-server/SECURITY.md}.
 */
public final class Protocol {
    public static final ObjectMapper MAPPER = new ObjectMapper();

    /**
     * Wire/data version for online play. Bumped when the protocol or the
     * snapshot format changes incompatibly; the lobby service records it so
     * mismatched clients can be warned instead of silently desyncing.
     */
    public static final String DATA_VERSION = "ic-net-2";

    private Protocol() {}

    /** Client -> server: introduce, carrying the guest's deck list for the host. */
    public record Hello(String type, String uuid, String name, DeckDto deck, String dataVersion) {
        public Hello(String uuid, String name, DeckDto deck) { this("hello", uuid, name, deck, DATA_VERSION); }
        public Hello {
            requireType(type, "hello");
            // Tolerate older clients that predate the field; the server rejects
            // them with a clear version-mismatch error instead of desyncing.
            if (dataVersion == null || dataVersion.isBlank()) dataVersion = "unknown";
        }
    }

    /** Client -> server: host requests the match to begin. */
    public record StartMatch(String type) {
        public StartMatch() { this("start"); }
        public StartMatch { requireType(type, "start"); }
    }

    /** Client -> server: one authoritative game command, e.g. {@code "play 0 1 2"}. */
    public record PlayerCommand(String type, String text) {
        public PlayerCommand(String text) { this("command", text); }
        public PlayerCommand { requireType(type, "command"); }
    }

    /** Server -> all: lobby roster. {@code players} is in seat order (host first). */
    public record Lobby(String type, List<LobbyPlayer> players, String hostUuid) {
        public Lobby(List<LobbyPlayer> players, String hostUuid) { this("lobby", players, hostUuid); }
        public Lobby { requireType(type, "lobby"); }
    }

    public record LobbyPlayer(String uuid, String name) {}

    /** Server -> all: authoritative result of one command, with a per-viewer snapshot. */
    public record StateUpdate(String type, long seq, String command, String result, int actor,
                              GameSnapshot snapshot) {
        public StateUpdate(long seq, String command, String result, int actor, GameSnapshot snapshot) {
            this("state_update", seq, command, result, actor, snapshot);
        }
        public StateUpdate { requireType(type, "state_update"); }
    }

    /**
     * Server -> all: full per-viewer state outside of a command (match start,
     * resync). {@code matchId} is generated by the host when the match starts
     * and is reported to the rating service by both clients at game over.
     */
    public record FullSnapshot(String type, long seq, String matchId, GameSnapshot snapshot) {
        public FullSnapshot(long seq, String matchId, GameSnapshot snapshot) {
            this("snapshot", seq, matchId, snapshot);
        }
        public FullSnapshot { requireType(type, "snapshot"); }
    }

    /** Server -> all: terminal match result, with a final per-viewer snapshot. */
    public record GameOver(String type, Integer winner, String matchId, GameSnapshot snapshot) {
        public GameOver(Integer winner, String matchId, GameSnapshot snapshot) {
            this("game_over", winner, matchId, snapshot);
        }
        public GameOver { requireType(type, "game_over"); }
    }

    /** Server -> one client: request rejected or session notice. */
    public record ErrorMessage(String type, String message) {
        public ErrorMessage(String message) { this("error", message); }
        public ErrorMessage { requireType(type, "error"); }
    }

    /**
     * Server -> one player: your opening hand is ready for a mulligan decision.
     * The snapshot is redacted for exactly this viewer; it carries the viewer's
     * own hand (full detail) so the client can render the choice UI.
     */
    public record MulliganPrompt(String type, long seq, String matchId, GameSnapshot snapshot) {
        public MulliganPrompt(long seq, String matchId, GameSnapshot snapshot) {
            this("mulligan_prompt", seq, matchId, snapshot);
        }
        public MulliganPrompt { requireType(type, "mulligan_prompt"); }
    }

    /**
     * Client -> server: this player's mulligan decision. {@code discardedCardIds}
     * holds up to 3 instance IDs from the player's own opening hand; empty
     * keeps the hand. The server validates every ID against the sender's hand.
     */
    public record MulliganDecision(String type, java.util.List<java.util.UUID> discardedCardIds) {
        public MulliganDecision(java.util.List<java.util.UUID> discardedCardIds) {
            this("mulligan", discardedCardIds == null ? List.of() : List.copyOf(discardedCardIds));
        }
        public MulliganDecision { requireType(type, "mulligan"); }
    }

    /** Server -> all: mulligan progress, in seat order. The match starts when both are true. */
    public record MulliganUpdate(String type, boolean decided0, boolean decided1) {
        public MulliganUpdate(boolean decided0, boolean decided1) { this("mulligan_update", decided0, decided1); }
        public MulliganUpdate { requireType(type, "mulligan_update"); }
    }

    /**
     * Server -> the reacting player only: a reaction window is open.
     * {@code commands} are the exact legal {@code "react ..."} command strings
     * the reactor may answer with (validated by exact match server-side);
     * the client should offer them and let the player pass. The reactor's own
     * hand is already visible in their latest snapshot.
     */
    public record ReactionPrompt(String type, long seq, String matchId, int reactingPlayer,
                                 List<String> commands, int expiresInSeconds) {
        public ReactionPrompt(long seq, String matchId, int reactingPlayer,
                              List<String> commands, int expiresInSeconds) {
            this("reaction_prompt", seq, matchId, reactingPlayer, List.copyOf(commands), expiresInSeconds);
        }
        public ReactionPrompt { requireType(type, "reaction_prompt"); }
    }

    /**
     * Client -> server: the reactor's answer. {@code command} must be one of the
     * strings from the matching {@link ReactionPrompt}; null or blank passes.
     */
    public record ReactionDecision(String type, String command) {
        public ReactionDecision(String command) { this("reaction", command); }
        public ReactionDecision { requireType(type, "reaction"); }
    }

    /** Server -> all: a reaction window expired without an answer and was auto-passed. */
    public record ReactionTimeout(String type, int player) {
        public ReactionTimeout(int player) { this("reaction_timeout", player); }
        public ReactionTimeout { requireType(type, "reaction_timeout"); }
    }

    private static void requireType(String actual, String expected) {
        if (!expected.equals(actual))
            throw new IllegalArgumentException("Expected type \"" + expected + "\" but got \"" + actual + "\"");
    }

    /** Serializes one envelope, terminated for the line-delimited transport. */
    public static String encode(Object message) {
        try {
            return MAPPER.writeValueAsString(message) + "\n";
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Cannot encode protocol message", e);
        }
    }

    /** Returns the {@code "type"} tag of one wire line, or throws on malformed JSON. */
    public static String typeOf(String line) {
        try {
            JsonNode node = MAPPER.readTree(line);
            JsonNode type = node.get("type");
            if (type == null || !type.isTextual()) throw new IllegalArgumentException("Missing type tag");
            return type.asText();
        } catch (JsonProcessingException e) {
            throw new IllegalArgumentException("Malformed protocol message", e);
        }
    }

    public static <T> T decode(String line, Class<T> type) {
        try {
            return MAPPER.readValue(line, type);
        } catch (JsonProcessingException e) {
            throw new IllegalArgumentException("Malformed protocol message", e);
        }
    }

    /**
     * Sanitizes a display name: strips control characters, trims, caps at 24
     * characters, and falls back to {@code "Player"}. Display names are public
     * (lobby, future leaderboards); UUIDs are never exposed in their place.
     */
    public static String sanitizeName(String raw) {
        if (raw == null) return "Player";
        String cleaned = raw.replaceAll("\\p{Cntrl}", "").trim();
        if (cleaned.isEmpty()) return "Player";
        return cleaned.length() > 24 ? cleaned.substring(0, 24) : cleaned;
    }
}
